from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_embedding(text):
    inputs = tokenizer(text, return_tensors='pt')
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze()

ingredient_text = "mushrooms"
ingredient_embedding = get_embedding(ingredient_text)

recipe_elements = [
    "diced tomatoes",
    "chopped onions",
    "garlic cloves",
    "egg white",
    "sliced mushrooms",
    "grated Parmesan cheese",
    "minced ginger",
    "cilantro leaves",
    "red chili flakes",
    "basil leaves",
    "ground cumin",
    "soy sauce",
    "sesame oil",
    "lime juice",
    "lemon zest",
    "honey",
    "apple cider vinegar",
    "dijon mustard",
    "chopped spinach",
    "coconut milk",
    "crushed black pepper",
    "oregano",
    "thyme leaves",
    "dill weed",
    "sliced bell peppers",
    "shredded mozzarella cheese",
    "heavy cream",
    "salted butter",
    "unsalted butter",
    "coriander powder",
    "paprika",
    "smoked paprika",
    "balsamic vinegar",
    "maple syrup",
    "sriracha sauce",
    "ketchup",
    "hoisin sauce",
    "peanut butter",
    "almond flour",
    "wheat flour",
    "cornstarch",
    "bread crumbs",
    "panko bread crumbs",
    "coconut oil",
    "olive oil",
    "canola oil",
    "sunflower oil",
    "vegetable broth",
    "chicken broth",
    "beef stock",
    "bay leaves",
    "rosemary sprigs",
    "ground nutmeg",
    "ground cinnamon",
    "ground turmeric",
    "ground coriander",
    "fennel seeds",
    "whole cloves",
    "star anise",
    "diced celery",
    "chopped carrots",
    "sliced cucumbers",
    "grated cheddar cheese",
    "chopped parsley",
    "ground cardamom",
    "brown sugar",
    "caster sugar",
    "powdered sugar",
    "vanilla extract",
    "almond extract",
    "unsweetened cocoa powder",
    "dark chocolate chips",
    "white chocolate chips",
    "rolled oats",
    "chia seeds",
    "flax seeds",
    "sliced avocado",
    "chopped green onions",
    "grated ginger",
    "whole grain mustard",
    "pesto sauce",
    "tomato paste",
    "crushed tomatoes",
    "sun-dried tomatoes",
    "chopped jalapeños",
    "pickled onions",
    "black olives",
    "green olives",
    "capers",
    "sliced zucchini",
    "shredded cabbage",
    "sliced radishes",
    "baby arugula",
    "baby spinach",
    "sliced almonds",
    "toasted pine nuts",
    "walnut pieces",
    "pecan halves",
    "dried cranberries",
    "raisins",
    "chopped apricots",
    "sliced peaches",
    "apple slices",
    "blueberries",
    "strawberries",
    "raspberries",
    "grapefruit segments",
    "orange slices",
    "cubed watermelon",
    "pomegranate seeds",
    "shredded coconut",
    "dried oregano",
    "red wine vinegar",
    "rice vinegar",
    "fish sauce",
    "tahini paste",
    "sesame seeds",
    "crushed peanuts",
    "panko breadcrumbs",
    "sourdough bread cubes",
    "whole wheat pasta",
    "cooked quinoa",
    "cooked brown rice",
    "wild rice",
    "bacon bits",
    "smoked salmon",
    "grated horseradish",
    "sliced prosciutto",
    "ground black pepper",
    "kosher salt",
    "sea salt",
    "herbes de Provence",
    "curry powder",
    "five spice powder",
    "ground white pepper",
    "diced shallots",
    "chopped basil",
    "fresh mint leaves",
    "fresh tarragon",
    "chopped dill",
    "sliced green beans",
    "edamame beans",
    "feta cheese crumbles",
    "ricotta cheese",
    "cream cheese",
    "goat cheese",
    "blue cheese crumbles",
    "brie cheese slices",
    "sour cream",
    "Greek yogurt",
    "plain yogurt",
    "crème fraîche",
    "mascarpone cheese",
    "buttermilk",
    "condensed milk",
    "evaporated milk",
    "whole milk",
    "oat milk",
    "almond milk",
    "soy milk",
    "rice milk",
    "beaten eggs",
    "whisked egg yolks",
    "hard-boiled eggs",
    "poached eggs",
    "scrambled eggs",
    "fried eggs",
    "cubed tofu",
    "sliced tempeh",
    "seitan strips",
    "cooked chickpeas",
    "black beans",
    "kidney beans",
    "cannellini beans",
    "pinto beans",
    "lentils",
    "split peas",
    "diced sweet potatoes",
    "chopped butternut squash",
    "cubed acorn squash",
    "sliced eggplant",
    "chopped broccoli florets",
    "cauliflower rice",
    "roasted Brussels sprouts",
    "sliced jalapeños",
    "diced red onions",
    "caramelized onions",
    "pickled jalapeños",
    "jalapeño slices",
    "baby corn",
    "canned artichoke hearts",
    "marinated mushrooms",
    "grated zucchini",
    "roasted garlic",
    "grilled corn kernels",
    "shredded chicken",
    "diced ham",
    "sliced roast beef",
    "cooked ground beef",
    "crumbled Italian sausage",
    "grilled chicken breast",
    "chopped turkey",
    "shredded pork",
    "pulled pork",
    "seared tuna",
    "grilled shrimp",
    "poached salmon",
    "smoked trout",
    "cooked mussels",
    "clams in garlic butter",
    "grilled scallops",
    "sliced squid rings",
    "diced haddock",
    "crab meat",
    "lobster tails",
    "shrimp cocktail",
    "fish fillets",
    "sliced tofu",
    "tempeh cubes",
    "nori sheets",
    "wasabi paste",
    "pickled ginger",
    "rice paper wrappers",
    "spring roll wrappers",
    "tortilla wraps",
    "lasagna sheets",
    "phyllo dough",
    "pizza dough",
    "focaccia bread",
    "baguette slices",
    "whole wheat pita",
    "naan bread",
    "corn tortillas",
    "flour tortillas",
    "roti",
    "ciabatta",
    "sourdough starter",
    "plain bagels",
    "sesame bagels",
    "everything bagels",
    "English muffins",
    "sliced sourdough",
    "cornbread",
    "banana bread",
    "zucchini bread",
    "cinnamon rolls",
    "croissants",
    "pain au chocolat",
    "apple turnovers",
    "eclairs",
    "chocolate chip cookies",
    "sugar cookies",
    "macarons",
    "muffins",
    "cupcakes",
    "brownies",
    "lemon bars",
    "fudge",
    "cheesecake",
    "fruit tart",
    "key lime pie",
    "apple pie",
    "pumpkin pie",
    "pecan pie",
    "strawberry shortcake",
    "angel food cake",
    "pound cake",
    "red velvet cake",
    "chocolate cake",
    "vanilla cake",
    "frosting",
    "whipped cream",
    "pastry cream",
    "chocolate ganache"
]

recipe_embeddings = [get_embedding(element) for element in recipe_elements]

from sklearn.metrics.pairwise import cosine_similarity

def find_closest_match(ingredient_embedding, recipe_embeddings):
    similarities = cosine_similarity(
        ingredient_embedding.unsqueeze(0),
        torch.stack(recipe_embeddings)
    )
    closest_index = similarities.argmax()
    return closest_index

closest_match_index = find_closest_match(ingredient_embedding, recipe_embeddings)
print(f"Closest match in recipe database: {recipe_elements[closest_match_index]}")